# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/jules/Documents/nonogram_solver/final_project_current.cache/wt [current_project]
set_property parent.project_path C:/Users/jules/Documents/nonogram_solver/final_project_current.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/jules/Documents/nonogram_solver/final_project_current.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/jules/Documents/nonogram_solver/coe/1_small.coe
add_files C:/Users/jules/Documents/nonogram_solver/coe/1_small_red.coe
add_files C:/Users/jules/Documents/nonogram_solver/coe/2_small.coe
add_files C:/Users/jules/Documents/nonogram_solver/coe/2_small_red.coe
add_files C:/Users/jules/Documents/nonogram_solver/coe/3_small_red.coe
add_files C:/Users/jules/Documents/nonogram_solver/coe/4_small.coe
add_files C:/Users/jules/Documents/nonogram_solver/coe/3_small.coe
add_files C:/Users/jules/Documents/nonogram_solver/coe/4_small_red.coe
add_files C:/Users/jules/Documents/nonogram_solver/coe/5_small.coe
add_files C:/Users/jules/Documents/nonogram_solver/coe/5_small_red.coe
add_files C:/Users/jules/Documents/nonogram_solver/coe/6_small.coe
add_files C:/Users/jules/Documents/nonogram_solver/coe/6_small_red.coe
add_files C:/Users/jules/Documents/nonogram_solver/coe/7_small.coe
add_files C:/Users/jules/Documents/nonogram_solver/coe/7_small_red.coe
add_files C:/Users/jules/Documents/nonogram_solver/coe/8_small.coe
add_files C:/Users/jules/Documents/nonogram_solver/coe/8_small_red.coe
add_files C:/Users/jules/Documents/nonogram_solver/coe/9_small.coe
add_files C:/Users/jules/Documents/nonogram_solver/coe/9_small_red.coe
add_files C:/Users/jules/Documents/temp_fodler/temp_fodler/nonogram_assignments.coe
read_verilog -library xil_defaultlib -sv {
  C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/new/assignments_registry.sv
  C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/new/create_a_row.sv
  C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/new/debounce.sv
  C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/new/display_hex.sv
  C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/new/eights_pixels.sv
  C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/new/fives_pixels.sv
  C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/new/fours_pixels.sv
  C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/new/generate_rows.sv
  C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/new/get_permutations.sv
  C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/new/iterative_solver_wth_reset.sv
  C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/new/manual_disp_10x10.sv
  C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/new/manual_disp_30_40.sv
  C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/new/nines_pixels.sv
  C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/new/ones_pixels.v
  C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/new/sevens_pixels.sv
  C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/new/sixes_pixels.sv
  C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/new/solved_disp.sv
  C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/new/threes_pixels.sv
  C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/new/top_level_solver.sv
  C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/new/translator.sv
  C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/new/twos_pixels.sv
  C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/new/xvga.sv
  C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/new/top_level_fresher.sv
}
read_verilog -library xil_defaultlib C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/new/clk_wiz_lab3.v
read_ip -quiet C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_one_rom/small_one_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_one_rom/small_one_rom_ooc.xdc]

read_ip -quiet C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_one_red_rom/small_one_red_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_one_red_rom/small_one_red_rom_ooc.xdc]

read_ip -quiet C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_two_rom/small_two_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_two_rom/small_two_rom_ooc.xdc]

read_ip -quiet C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_two_red_rom/small_two_red_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_two_red_rom/small_two_red_rom_ooc.xdc]

read_ip -quiet C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_three_red_rom/small_three_red_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_three_red_rom/small_three_red_rom_ooc.xdc]

read_ip -quiet C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_four_rom/small_four_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_four_rom/small_four_rom_ooc.xdc]

read_ip -quiet C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_three_rom/small_three_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_three_rom/small_three_rom_ooc.xdc]

read_ip -quiet C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_four_red_rom/small_four_red_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_four_red_rom/small_four_red_rom_ooc.xdc]

read_ip -quiet C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_five_rom/small_five_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_five_rom/small_five_rom_ooc.xdc]

read_ip -quiet C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_five_red_rom/small_five_red_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_five_red_rom/small_five_red_rom_ooc.xdc]

read_ip -quiet C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_six_rom/small_six_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_six_rom/small_six_rom_ooc.xdc]

read_ip -quiet C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_six_red_rom/small_six_red_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_six_red_rom/small_six_red_rom_ooc.xdc]

read_ip -quiet C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_seven_rom/small_seven_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_seven_rom/small_seven_rom_ooc.xdc]

read_ip -quiet C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_seven_red_rom/small_seven_red_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_seven_red_rom/small_seven_red_rom_ooc.xdc]

read_ip -quiet C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_eight_rom/small_eight_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_eight_rom/small_eight_rom_ooc.xdc]

read_ip -quiet C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_eight_red_rom/small_eight_red_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_eight_red_rom/small_eight_red_rom_ooc.xdc]

read_ip -quiet C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_nine_rom/small_nine_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_nine_rom/small_nine_rom_ooc.xdc]

read_ip -quiet C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_nine_red_rom/small_nine_red_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/small_nine_red_rom/small_nine_red_rom_ooc.xdc]

read_ip -quiet C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/assignments_rom/assignments_rom.xci
set_property used_in_implementation false [get_files -all c:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/sources_1/ip/assignments_rom/assignments_rom_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/constrs_1/new/constraints.xdc
set_property used_in_implementation false [get_files C:/Users/jules/Documents/nonogram_solver/final_project_current.srcs/constrs_1/new/constraints.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_level_fresher -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_level_fresher.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_level_fresher_utilization_synth.rpt -pb top_level_fresher_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
